# Generated by Django 4.1.2 on 2022-11-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_roundvideo_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundvideo',
            name='chat_tg_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
