# Generated by Django 4.1.2 on 2022-11-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_users_roundvideo_code_in_video_roundvideo_id_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundvideo',
            name='type_video',
            field=models.CharField(choices=[('test', 'Test'), ('dispute', 'Dispute'), ('archive', 'Archive')], default='none', max_length=20, verbose_name='Тип видео'),
        ),
        migrations.AlterField(
            model_name='roundvideo',
            name='status',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad'), ('other', 'Other')], max_length=20, verbose_name='Статуexitс кружочка'),
        ),
    ]
