# Generated by Django 4.1.2 on 2022-11-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_support_alter_roundvideo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('faq_num', models.IntegerField()),
            ],
        ),
    ]
