# Generated by Django 4.1.2 on 2022-11-18 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_remove_faq_id_roundvideo_in_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundvideo',
            name='in_progress',
        ),
    ]
