# Generated by Django 4.1.2 on 2022-11-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_remove_roundvideo_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundvideo',
            name='n_day',
            field=models.IntegerField(default=0),
        ),
    ]
