version: "3.9"

services:

  bot_admin:
    restart: always
    build:
      context: ./
      dockerfile: python/Dockerfile.admin_bot

    environment:
      DJANGO_SETTINGS_MODULE: settings.settings
    depends_on:
      - redis
  bot_client:
    restart: always
    build:
      context: ./
      dockerfile: python/Dockerfile.client_bot
    environment:
      DJANGO_SETTINGS_MODULE: settings.settings
    depends_on:
      - redis


  redis:
    restart: always

    image: redis:7.0.3
    volumes:
      - ./redis/redis-data:/var/lib/redis
