version: "3.9"

services:

  bot_admin:
    restart: always
    build:
      context: ./
      dockerfile: python/Dockerfile.admin_bot

    environment:
      DJANGO_SETTINGS_MODULE: settings.settings
    env_file:
      - ./src/settings/config.env
    volumes:
      - ./src:/src/AdminBot
    depends_on:
      - redis
      - postgres
  bot_client:
    restart: always
    build:
      context: ./
      dockerfile: python/Dockerfile.client_bot
    environment:
      DJANGO_SETTINGS_MODULE: settings.settings
    env_file:
      - ./src/settings/config.env
    volumes:
      - ./src:/src/ClientBot
    depends_on:
      - redis
      - postgres

  redis:
    restart: always

    image: redis:7.0.3
    volumes:
      - ./redis/redis-data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  postgres:
    restart: always
    image: postgres:14.4
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file:
      - ./src/settings/config.env
    ports:
      - "5432:5432"


