# Generated by Django 4.1.4 on 2022-12-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_periodictask_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictask',
            name='day_of_week',
            field=models.CharField(default='*', max_length=20, verbose_name='В какой час вызвать'),
        ),
    ]
