# Generated by Django 4.1.4 on 2022-12-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_periodictask_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodictask',
            name='job_id',
            field=models.CharField(max_length=255, verbose_name='id задачи'),
        ),
    ]
