# Generated by Django 4.1.4 on 2022-12-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_user_timezone_alter_user_number_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_mistakes',
            field=models.IntegerField(default=0, verbose_name='количество попыток'),
            preserve_default=False,
        ),
    ]
