# Generated by Django 4.1.4 on 2022-12-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_user_count_mistakes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('chat_id', models.BigIntegerField()),
                ('user_name', models.CharField(max_length=20, verbose_name='Имя игрока')),
                ('id_dispute', models.IntegerField(verbose_name='Уникальный идентификатор диспута')),
                ('city', models.CharField(max_length=30, verbose_name='Город игрока')),
                ('mark', models.CharField(max_length=10, verbose_name='кол-во звёзд')),
                ('coment', models.CharField(max_length=256, verbose_name='комментарий')),
                ('state_t', models.CharField(choices=[('done', 'Done'), ('bad_review', 'Bad Review'), ('new', 'New')], max_length=10, verbose_name='статус отзыва')),
            ],
        ),
    ]
