# Generated by Django 4.1.5 on 2023-01-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundvideo',
            name='tg_id',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='action',
            field=models.CharField(max_length=20, verbose_name='Тип диспута'),
        ),
        migrations.AlterField(
            model_name='user',
            name='additional_action',
            field=models.CharField(max_length=20, verbose_name='Дополнительное условие диспута'),
        ),
    ]
