# Generated by Django 4.1.5 on 2023-01-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_alter_roundvideo_tg_id_alter_user_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodictask',
            name='fun',
            field=models.CharField(max_length=255, verbose_name='Название периодической функции'),
        ),
    ]
