# Generated by Django 4.1.7 on 2023-03-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_periodictask_is_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictask',
            name='month',
            field=models.CharField(default='*', max_length=20, verbose_name='В какой месяц вызывать'),
        ),
        migrations.AlterField(
            model_name='periodictask',
            name='day_of_week',
            field=models.CharField(default='*', max_length=20, verbose_name='В какой день недели вызывать'),
        ),
    ]
