# Generated by Django 4.1.7 on 2023-03-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_periodictask_month_alter_periodictask_day_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogerPromocodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode', models.CharField(max_length=10, verbose_name='Уникальный промокод для блогера')),
            ],
        ),
    ]
