# Generated by Django 4.1.7 on 2023-04-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_disputeadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputeadmin',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='id пользователя в рамках админ бота'),
        ),
    ]
