# Generated by Django 4.1.9 on 2023-06-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_disputeadmin_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogerpromocodes',
            name='is_issued',
            field=models.BooleanField(default=False, verbose_name='Выдан ли промокод?'),
        ),
    ]
