# Generated by Django 4.1.10 on 2023-07-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_blogerpromocodes_is_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_change_tz',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата и время последнего изменения'),
        ),
    ]
