# Generated by Django 4.1.10 on 2023-07-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_user_last_change_tz'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.BigIntegerField(default='567890'),
            preserve_default=False,
        ),
    ]
